### ISSUE TITLE
IBBM-ExtractSimpleIsosurface input isovalues; output missing one isosurface 

### ISSUE THREAD

**Issue by brikindall** [SCIInstitute/SCIRun#1110]
This is from the Isosurfacing_Cube example net IBBM 2015 directory. The module ExtractSimpleIsosurface has a bug in which it outputs one less isosurface in response to any number of isovalue inputs, specifically under the list tab in the UI.
<img width="859" alt="screen shot 2015-07-09 at 12 51 52 pm" src="https://cloud.githubusercontent.com/assets/12752309/8604064/6ad7e000-2639-11e5-9390-817dd43b020a.png">

**Comment by dcwhite** [comment]
@jessdtate will test this one again, it might be fixed.

**Comment by jessdtate** [comment]
This effect is a result of the data in that when the min and max of the field data are used as isosurface values (the default of the module), the min and max isosurfaces are small or non-existent.  Since these values are by definition on the extremes of the range of the field values, it is mathematically impossible to generate a meaningful boundary surface along the value.  a point, or a single small element may be generated, as in the case for the max of this example, but it will not be visible.  

There are new features in the ExtractIsosurface module (exclusive and alternate min/max) which allow the users to generate the desired number of isosurfaces in a meaningful way.
