### ISSUE TITLE
Adjust alpha hues in createstandardcolormap MLM

### ISSUE THREAD

**Issue by cbrightsci** [SCIInstitute/SCIRun#1201]

**Comment by dcwhite** [comment]
@cbrightsci I have a basic alpha-editing GUI, and now need to pass those values into the ColorMap object. However, it looks like ShowField just applies a universal transparency rather than using the colormap value (which is not even used, 1.0 is passed to the VBO). I'll need some help figuring that part out.

**Comment by cbrightsci** [comment]
@dcwhite We're going to have to make some changes to how transparency and vertices are being setup to get these new alpha values in to their spots.

**Comment by dcwhite** [comment]
That's what I thought. I'll aim to get the alpha values available next week.
