### ISSUE TITLE
SCIRun 4 network import, part 2

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1219]
Continue writing state and name mapping code for every module. Modules will be done by priority/upon request. Follows #1070.

**Comment by dcwhite** [comment]
Students and interns needed.

**Comment by dcwhite** [comment]
A good lunch hack-a-thon! @jessdtate will organize.

**Comment by Nahusa** [comment]
Modules not implemented : 

ViewScene
ExtractIsosurface
SplitFieldIntoNrrdData
ConvertNrrdToField
ReadNrrd
ReportNrrdInfo
BuildDerivedNrrdWithGage
ImportFieldsFromMatlab
GenerateSinglePointProbeFromField
WriteMatrix
ReportColumnMatrixMisfit
CreateGeometricTransform
InsertFieldsIntoBundle
ShowString
BuildBEMatrix
ConvertMatrixType
ImportMatricesFromMatlab
ResampleRegularMesh
GetMatricesFromBundle
InsertMatricesIntoBundle
GetColumnOrRowFromMatrix

**Comment by Nahusa** [comment]
Modules partially done : 

| Module | Variables not used in V5 | Variables not implemented (mostly due to the one-to-many mapping issue) |
| :---         |     :---:      |          ---: |
|ShowField	|faces_usetexture|	nodes_display_type|
||nodes_scaleNV	|edges_display_type|
||edges_scaleNV	||
||active_tab 	||
||interactive_mode	||
||showProgress	||
||gui_field_name_override	||
||approx_div	||
||gui_use_default_size	||
|CreateStandardColorMap	||	reverse|
|||faux|
|||position_list|
|||node_list|
|||width|
|||height|
|ShowFieldGlyphs	|scalars_has_data_	|scalars_display_type_|
||scalars_small_is_dot_	|vectors_display_type_|
||scalars_normalize_	|tensors_display_type_|
||scalars_scaleNV_	||
||scalars_threshold_	||
||scalars_thresholdNV_	||
||vectors_has_data_	||
||vectors_normalize_	||
||vectors_scaleNV_	||
||vectors_threshold_	||
||vectors_thresholdNV_	||
||vectors_bidirectional_	||
||vectors_small_is_dot_	||
||tensors_has_data_	||
||tensors_normalize_	||
||tensors_scaleNV_	||
||tensors_threshold_	||
||tensors_thresholdNV_	||
||tensors_emphasis_	||
||tensors_small_is_dot_	||
||secondary_*	||
||tertiary_*	||
||text_*	||
||active_tab	||
||interactive_mode_	||
||showProgress_	||
||gui_field_name_	||
||gui_field_name_override_	||
||approx_div_	||
||gui_use_default_size_	||
|EditMeshBoundingBox	|widget_scale	|restrict_translation|
||widget_mode	||
||box_scale	||
||box_mode_	||
||box_real_scale_	||
||box_center_	||
||box_right_	||
||box_down_	||
||box_in_	||
||resetting_	||
|GetSliceFromStructuredFieldByIndices	|	|update_type|
|SolveLinearSystem	|orig_error	||
||current_error	||
||iteration	||
||use_previous_soln	||
||emit_partial	||
||emit_iter	||
|ShowColorMap	|extra-padding	|text-fontsize|
|WriteField	|confirm|	|filetype|
||confirm-once	||
||exporttype	||
||increment	||
||current	||
|SolveInverseProblemWithTikhonov	|lambda_from_scale	||
||have_ui	||

**Comment by dcwhite** [comment]
Thanks for this summary!
