### ISSUE TITLE
Viewscene matrix output is blue channel only

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#1328]
The matrix output port in the viewscene module passes a matrix of the blue channel of the image in the view scene.  This make the matrix not very useful for users, but also has an impact on regression testing that uses this output.  Attached is the image in the view scene and from the matrix port (in grayscale).
![viewscene_2016 02 19 172213 863_1](https://cloud.githubusercontent.com/assets/3484631/13192841/863aee8c-d72d-11e5-93fd-cb7f70f9fd9f.png)
![matrix_output](https://cloud.githubusercontent.com/assets/3484631/13192848/971987ae-d72d-11e5-858f-5cce69f8248a.jpg)

**Comment by dcwhite** [comment]
The code for converting the screenshot image to matrix is crap. The fix should be easy. What's the quickest way to visualize the matrix as a picture, like you did above?

**Comment by jessdtate** [comment]
I just loaded it into matlab and used imagesc. You can do it in python with the following code:
`import numpy as np
import matplotlib.image as mpi

mat = MatrixInput1

matrix=np.array(mat)

print(type(matrix))

mpi.imsave('/Users/jess/software/SCIRunTestData/mat_image.png', matrix)'

**Comment by dcwhite** [comment]
@jessdtate When Matlab reads an image, it converts it into a 3-D matrix with one 2-D matrix per RGB channel, ranging from 0-255. So essentially the code right now outputs one slice of this representation, the blue slice. In order to match this format, what sort of module output would you prefer? I can send a bundle of 3 matrices, or have 3 matrix output ports, or ?? Let me know.

**Comment by dcwhite** [comment]
I could also send a 3-D Nrrd object.

**Comment by jessdtate** [comment]
The most intuitive is the three matrices, but any of these could work.
