### ISSUE TITLE
Font Control in ViewScene Across Modules

### ISSUE THREAD

**Issue by butsonc** [SCIInstitute/SCIRun#1334]
We use text in the Viewer often, and it seems like the names for text sizes could be more consistent across modules. For example, ShowField lists the sizes XS to XL, ShowString lists sizes from Tiny to Huge, ShowColorMap lists sizes from T to XL. More importantly, we often need larger text sizes than are available. I realize that some text is in a separate layer that sits on top of the scene, while other text is used to label elements such as nodes and can be zoomed in and out.

One idea: add more size options such as "yuge", ginormous or Brobdingnagian to the font size choices.

Alternately it might be better if we could specify the font size. It would also be great to have the same font control options across modules.

**Comment by dcwhite** [comment]
:+1:

**Comment by cbrightsci** [comment]
I think you are absolutely correct. Though getting the quantifiable values for the names was a challenge, I feel that the end results turned out great. I also made it so you can actually see what each size description might look like by giving a display of it in the GUI. But I'll let the beautiful results speak for themselves. 

![image](https://cloud.githubusercontent.com/assets/8061225/13434042/b6e6b6b2-df91-11e5-8ab3-fcf4dc991330.png)

**Comment by butsonc** [comment]
Hmm. Isn’t Yuge between L and XL? Let’s ask Donald Trump...

:)

**Comment by cbrightsci** [comment]
You're right! I guess that's what test lunches are for. :)
