### ISSUE TITLE
ShowField - can't deselect faces/nodes/edges

### ISSUE THREAD

**Issue by lizutah** [SCIInstitute/SCIRun#1437]
@johaenns will reproduce and report back (using linux)

**Comment by aylakhan** [comment]
@johaenns - any updates?

**Comment by johaenns** [comment]
Currently I would assume that there is no bug.

The point rather is that -- unlike scirun4 -- scirun5 updates all connected modules when changing simple settings in ViewScene like selecting/deselecting "Show Edges", "Show Faces", etc. Since this can take a couple of seconds, it gave me the appearance that I couldn't select/deselect certain features.

Though there seems to be no bug, I wonder if this is a wanted/necessary behavior? It makes the inspection of results generated by large networks pretty tedious, as every change of the visualization, be it directly in ShowField or a change/rescaling of the colormap or similar, takes a couple of seconds. To be able to efficiently work with scirun5 this way, it would be necessary to split nets up, which would again limit the possibilities in the workflow...

I don't know if this was discussed before and if this is intentional, I couldn't find a related issue?

**Comment by dcwhite** [comment]
This now falls under the general network/GUI performance umbrella (#1065 etc). The issue is the GUI thread--it's not optimized at all. You're right, when no module actually needs to execute (even though every module must check if it needs to), re-execution should be much faster. I ought to be able to look at this during IBBM and get a quick fix in for ShowField/ViewScene.
