### ISSUE TITLE
Unable to run scirun-net with "-e"/"-E" in headless built

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/SCIRun#1545]
Trying to execute a scirun-net in the headless built using "-e"/"-E" option leads to a crash with output

HEADLESS MODE
Attempting load of empty.srn5
2016-08-25 10:16:26.047  [INFO] module position editor unavailable, module positions at default
File load done: empty.srn5
Goodbye!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted

Execution in normal build with "--headless --no_splash" and "-e"/"-E" works fine, execution of a scirun-net via a python script using "-s" also works fine.

Steps to reproduce:

1. create a scirun-net (may even be empty...)
2. call a headless build with "-e"/"-E" and the generated python script.

### Versions
SCIRun v5.0-beta.D-14-gfb379f3
Opensuse Leap

**Comment by dcwhite** [comment]
@johaenns This is a problem with the command dependencies. As a workaround for right now, add `-i` to any command. This will load/execute the file/script and then give you a prompt. I will soon merge a fix that allows the use of ^C or ^D to then exit. The fix for this issue will enable proper handling of -e/-E with headless.
