### ISSUE TITLE
Using python to add modules isn't working

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1656]
If you use python to add a module, whether from the python console, calling a python script at launch with -s, or calling a script from the GUI, the module exists in memory and can be interacted with via other python code, but it doesn't show up in the GUI. If you then try to execute the network, you get a seg fault. If you use python to load a network, and then change module states, the network loads in the GUI, and execution works as expected.

This bug needs to be fixed before IBBM

**Comment by jessdtate** [comment]
I see the same thing.  Here is my crash report:

Process:               SCIRun_test [26463]
Path:                  /Users/USER/*/SCIRun_test
Identifier:            SCIRun_test
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [658]
Responsible:           SCIRun_test [26463]
User ID:               501

Date/Time:             2017-06-23 11:43:23.845 -0600
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        220015BF-3AFA-BDBE-20F8-B7EED265C4B9

Sleep/Wake UUID:       4750B530-7F44-4F28-B27A-B2B59625DEC1

Time Awake Since Boot: 31000 seconds
Time Since Wake:       2100 seconds

System Integrity Protection: enabled

Crashed Thread:        15

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 000000010ff31000-000000010ff51000 [  128K] r-x/rwx SM=COW  /Users/USER/*

Thread 15 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x000000000005b760
  rdi: 0x000070000377de20  rsi: 0x00007fdb1be00000  rbp: 0x000070000377de80  rsp: 0x000070000377dda0
   r8: 0x0000000000000007   r9: 0x00007fdb16cc9b80  r10: 0x0000000000000001  r11: 0x0000000000000008
  r12: 0x000000011007d8e0  r13: 0x0000000000011807  r14: 0x00007fdb18eac980  r15: 0x000070000377de20
  rip: 0x000000011148c3e7  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

**Comment by dcwhite** [comment]
This bug affects all pathways for adding a module. Here is a list, am I missing any?
- [ ] Double-click in selector
- [ ] Drag from selector
- [ ] loading a file
- [ ] Replacing a module
- [ ] Adding a new module/connection through a port
- [ ] Adding a new module with Insert module
- [ ] `scirun_add_module` from the python console
- [ ] `scirun_add_module` in a script, run from wand button
- [ ] `scirun_add_module` in a script, run from command line with `-s`

**Comment by gduffley** [comment]
Those are more ways than I was even aware of. One comment I have is I don’t actually think this bug is that important. How I envision (and currently use) python with SCIRun is to prototype a network in the GUI, then use python to make changes to variables. Although it is cool, I actually don’t know how important it is to be able to add modules to a network, as long as they can be rewired and state variables can be changed. I could easily modify my IIBM lab to avoid using the create module functionality.

**Comment by dcwhite** [comment]
I fixed almost all the cases, replace is being fixed today. PR coming soon
