### ISSUE TITLE
repair_package is broken

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#1687]
There's no "plist" file being generated--need this for a build for @buuuurak.

**Comment by dcwhite** [comment]
User error for me--BUILD_BUNDLE was turned off. But @jessdtate saw a different error--can you update this issue Jess?

**Comment by jessdtate** [comment]
when building the SCIRun.app, I get the following errors:

ERROR: no file at "/Library/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL.framework/Versions/4/QtOpenGL"
ERROR: no file at "/Library/Frameworks/QtGui.framework/Versions/4/QtGui.framework/Versions/4/QtGui"
ERROR: no file at "/Library/Frameworks/QtNetwork.framework/Versions/4/QtNetwork.framework/Versions/4/QtNetwork"
ERROR: no file at "/Library/Frameworks/QtCore.framework/Versions/4/QtCore.framework/Versions/4/QtCore"
ERROR: no file at "/Users/jess/software/SCIRun_mine/bin/Externals/Install/lib/Python.framework/Versions/3.4/Python"
ERROR: Unexpected prefix "@loader_path"
ERROR: Unexpected prefix "@loader_path"
ERROR: Unexpected prefix "@loader_path"
ERROR: Unexpected prefix "@loader_path"

it seems that the paths should be /Library/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL, etc, because those files exist.

**Comment by dcwhite** [comment]
Can you attach the entire build log? I don't see `@loader_path` used anywhere in the cmake.

**Comment by dcwhite** [comment]
@jessdtate Any further problems with this?

**Comment by dcwhite** [comment]
Still need that build log...

**Comment by jessdtate** [comment]
Here are the logs.  for the total build:
[error.txt](https://github.com/SCIInstitute/SCIRun/files/1363896/error.txt)
[results.txt](https://github.com/SCIInstitute/SCIRun/files/1363895/results.txt)
and for just SCIRun (minus the externals)
[error.txt](https://github.com/SCIInstitute/SCIRun/files/1363898/error.txt)
[results.txt](https://github.com/SCIInstitute/SCIRun/files/1363899/results.txt)

**Comment by dcwhite** [comment]
Which OSX and Qt are you using?

**Comment by jessdtate** [comment]
This is on os x 10.10 and qt 4.8.5.

**Comment by dcwhite** [comment]
I built an installer with no problems on my 10.10 machine. I suggest you start your build over from scratch.

**Comment by dcwhite** [comment]
@jessdtate Is this still an issue? Test on 10.12 or 13 with Qt5, as Qt4 support will be dropped soon.

**Comment by jessdtate** [comment]
yeah, this seems to have been resolved with qt5
