### ISSUE TITLE
Warning Indication for missing modules

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/SCIRun#1773]
### Description

It would be nice if there was a warning indication when a module from a previously created SCIRun network does not exist in the current build that is loading the SCIRun network. For example, if you are using a build that does not have the Tetgen functionality SCIRun will simply eliminate the module within the network and does not provide any error message that "tetgen" or the specific module was not loaded.

**Comment by dcwhite** [comment]
This is logged, but it's buried quite deeply right now (Window->Log->Main Log->Open Log Folder->open missingModules.log file). I will move it to the main log window, and also add a pop-up for the Tetgen case since that is common.

**Comment by dcwhite** [comment]
@bzenger The way the code is, I can make an easy change to display a pop-up warning message, but the rest of the network will not be loaded. It will be more complicated to display the warning message as a pop-up AND load the rest of the network without TetGen (the way it is now), but I bet in most cases this will not be that helpful, since it's usually a key module. Is that OK?

**Comment by bzenger** [comment]
Yeah that would work well I think!
