### ISSUE TITLE
SetProperty 

### ISSUE THREAD

**Issue by OGharbia** [SCIInstitute/SCIRun#1847]
Hello,

I used to use SCIRun 4.7 to run BuildBEMatrix in which I load two matrixes (Heart&Torso) using ImportFieldsFromMatlab, and then I use SetFieldOreshStringProperty to set the properties for the input data. Now,I updated my OS to 10.14. So, I had to download SCIRun 5, because the old version SCIRUn 4.7 is not compatible with the new version of OS 10.14, but I could not find any way to set property, which was called SetFieldOreshStringProperty in SCIRun 4.7. I am wondering whether you changed its name to something else or stopped supporting it. Could you please help me solve this problem.

Thank you,

Omar

**Comment by dcwhite** [comment]
The property functionality is still enabled for data objects in SCIRun 5, but that module has not been converted so there is no way to access them. We're thinking of phasing out properties anyway since the UI support was so lacking. If you could share a simple example network in v4 format, @jessdtate could help figure out a way to design the v5 network. If he is stuck, we can discuss implementing some property-enabling features.

**Comment by OGharbia** [comment]
![scirun_network](https://user-images.githubusercontent.com/44846118/48171403-c4a12880-e2c9-11e8-8267-42adc1a1567e.png)

This a screenshot of BEM network that I used to run using 4.7. I hope this screenshot help you figure something out that can help me run the BEM again.

**Comment by jessdtate** [comment]
The later versions of SCIRun 4.7 and SCIRun 5 allow you to set these parameters in the BuildBEMatrix module, therefore the properties modules are not needed.  Unfortunately, the examples were not properly updated to reflex this.  As seen in the image, the inside and outside conductivities are set in the BuildBEMatrix module.  The in/out property is now the measurement (out) or source (in) parameter.  These are the same in SCIRun 5.  You can also check out the newer version of the Fwd/inv toolkit for the example (https://github.com/SCIInstitute/FwdInvToolkit)
