### ISSUE TITLE
Upgrade GLM version

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2067]
We're on a very old tag (almost 3000 commits have been added). There was just a new release (still pre-1.0), but it might have newer language features, like {}-initialization.

**Comment by RubioJr9** [comment]
Major changes in glm between 0.9.4.6  to  0.9.9.7:

Features:
-Added forward declarations (glm/fwd.hpp) for faster compilations
-Added C++11 initializer lists(@dcwhite called it)
-Added GTC_color_space: convertLinearToSRGB and convertSRGBToLinear functions
-Added <glm/gtx/hash.hpp> to perform std::hash on GLM types

Bug Fixes:
-Fixed bug where calling fast*() vectorized functions caused errors
-Fixed Clang build on Windows
-Fixed orthographic projection
-Lots more

Math:
-Scalar multiplication
-Option between [-1,1] or [0,1] for depth buffer range
-Range Support 
Ex.    glm::vec3 v(1,2,3);
         for(auto x : v)
           cout << x << endl;

Vectors:
-vec3 slerp()
-vec_swizzle class
  Instead of vector.xy, you call function xy(vector)

Quaternions:
-Added rotate(quat from, quat to)
-Comparison functions
-Added to_string()
-Added lookAt(vec direction, vec up)
-Fixed Quaternion storage order inconsistency
-Flag to choose between x,y,z,w and w,x,y,z orderings

Deprecation:
-Deprecated degrees for function parameters and display a message
-Requires Visual Studio 2013, GCC 4.7, Clang 3.4, Cuda 7, ICC 2013 or a C++11 compiler
-Removal of default initialziation for vector, matrix, quaternion (you can restore old behavior with a flag)
-Removed GLM_SWIZZLE, use GLM_FORCE_SWIZZLE instead(replaced with vec_swizzle)

**Comment by dcwhite** [comment]
Thanks. Sounds like we definitely need to upgrade. Let's discuss at the meeting today

**Comment by dcwhite** [comment]
@RubioJr9 Want to work on this one next while I work on #2077? It should avoid merge issues, hopefully.

**Comment by RubioJr9** [comment]
Good idea

**Comment by dcwhite** [comment]
@RubioJr9 I just noticed this new feature
> -Removal of default initialziation for vector, matrix, quaternion (you can restore old behavior with a flag)
Oops, that flag would've solved the constructor problem in one stroke. Do you want to still enable it, to catch possible new confusion, or keep it off and try to adopt the new semantics?

**Comment by RubioJr9** [comment]
> @RubioJr9 I just noticed this new feature
> 
> > -Removal of default initialziation for vector, matrix, quaternion (you can restore old behavior with a flag)
> 
> Oops, that flag would've solved the constructor problem in one stroke. Do you want to still enable it, to catch possible new confusion, or keep it off and try to adopt the new semantics?

Oh I forgot that they added a flag for that. It seems that the new default is to initialize all elements to 0, which does not make very much sense for matrices and quaternions. There's a flag to disable initializing values entirely, so they hold garbage data on default construction. Better yet, we can just do that explicitly if we ever need to: `glm::vec4 v(glm::uninitialize);` I think we should stick to constructing the identity on default. The flag for it is: `GLM_FORCE_CTOR_INIT`
