### ISSUE TITLE
ExportFieldsToMatlab fails without data on field

### ISSUE THREAD

**Issue by Sumientra** [SCIInstitute/SCIRun#2080]
**Describe the bug**
When using ExportFieldsToMatlab the module will show an error and will not save the file if there is no data on the field: 
<img width="421" alt="Screen Shot 2020-03-05 at 13 35 14" src="https://user-images.githubusercontent.com/20671873/76023794-1b7f3800-5ee7-11ea-8e33-7055c4144613.png">
The ExportFieldsToMatlab module does work if there is data on the field. 
The WriteField module does save to .mat without data on the field. This is what EFTM should do as well.

**To Reproduce**
1. Load or create a mesh in SCIRun that does not have any data on it.
2. Connect to ExportFieldsToMatlab and run it.

**Expected behavior**
It should create a .mat file that contains the field (regardless of whether there is data on it).

**Version**
v5.0-beta.X.RC1

**Desktop**
10.14.16

**Comment by dcwhite** [comment]
Did you try using struct array rather than numeric array? From the code it looks like with numeric array output, it will save the field data only, so an error would be expected in this case. @jessdtate Does that match your thinking?

**Comment by jessdtate** [comment]
I suppose it could be, but don't think that is what the error is. If you have a numeric array in the file, the converter will try to make the values into an image mesh with the array values as field data, as far I know.   I looks to me like the exporter doesn't have the same flexibility.  This is probably because, I think, the only way to get this error is this kind of pass through.  Every other module operation that I have used generates some data.  I also get an error in Writefield, but it is less helpful: "Export failed".  

Another caveat, I can't get importfieldsfrommatlab to work with this file, but it works in readfield, so I replicated the bug with that instead. 
[sock.mat.zip](https://github.com/SCIInstitute/SCIRun/files/4314619/sock.mat.zip)

**Comment by Sumientra** [comment]
Jup, that was it. Turns out in SCIRun 4 the default for EFTM was 'struct array' so it always worked as I expected, but in SCIRun 5 the default is 'numeric array' so doing the same thing I've always done suddenly doesn't work anymore. WriteField doesn't have the option and just saves to struct automatically, so it always works. Think it would be good to either remove the numeric array option from the field exporter or convert it to an all-purpose exporter.

**Comment by dcwhite** [comment]
I can change that default. I didn't have v4 running to compare, but I can do that today.
