### ISSUE TITLE
Review module defaults

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#2083]
Discussed today:
- [ ] Reader input file types -> matlab
- [ ] Writer output file types -> matlab
- [x] ClipFieldByFunction @wgood 
- [x] MFDFSTD @wgood 
- [x] RWC @wgood

**Comment by wgood** [comment]
ClipFieldByMesh @wgood (The default for ClipFieldbyfunction should be elementcenter instead of onenode. )
 MFDFSTD @wgood (The default for  MFDFSTD should be Constant Mapping: Each Destination Gets Nearest Source Value instead of Linear)
 RWC @wgood (The Default should be Affine or Rigid instead of Morph)

**Comment by dcwhite** [comment]
Thanks!

**Comment by dcwhite** [comment]
@wgood After recent discussions with @jessdtate and @jab0707, I'm going to try making a new "SmartReader" module from scratch that will have user-defined defaults, or just default to Matlab for everything. I had trouble with modifying the ancient legacy readers, and it would be cool to just have one read module that can handle everything. It will subsume issues #1216, #289, #2110, and this one.
