### ISSUE TITLE
BuildBEMatrix and Python interface

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2162]
The BuildBEMatrix module does not play well with the interface with python. The conductivity lists seem to be available as python state variables, however any attempt to change them using python does not work. the associated error messages also do not show why the issue is occurring at first glance.

There should be a way to use scirun_set_module_state('BuildBEMatrix:0', 'InsideConducitivtyList', [0, 1]) for an example with two surfaces. 
@dcwhite mentioned that this may be fixed using some code that was written to allow python manipulation of the viewscene camera angle.

**Comment by RubioJr9** [comment]
Hi Jake, I originally changed ViewScene CameraRotation and CameraLookAt to strings so they can be edited from python, but that was less than ideal since you had to convert to and from strings.

The good news is that calling scirun_set_module_state() with python lists is coming soon! There's an issue #2054 and I have an open pull request for it now #2149. I just need to fix an issue and do more testing. I also made scirun_get_module_state() return these variable lists as python lists so this would be valid code:
`pythonList = scirun_get_module_state("ViewScene:0", "CameraLookAt")
pythonList[1] = 3.5
scirun_set_module_state("ViewScene:0", "CameraRotation", pythonList)`

**Comment by dcwhite** [comment]
@jab0707 This does work better now that the list handling is incorporated into the set/get state calls. Can you try with the latest build? I was able to do this:

```
>>> scirun_set_module_state(m, "InsideConductivityList", [1,1])
'Value set'
>>> scirun_get_module_state(m, "InsideConductivityList")
[1, 1]
```

**Comment by dcwhite** [comment]
@jab0707 👀

**Comment by jab0707** [comment]
I will try rebuilding and get back with results

**Comment by dcwhite** [comment]
@jab0707 👀 👀

**Comment by dcwhite** [comment]
@jab0707 👀 👀 👀

**Comment by jab0707** [comment]
Yep, that looks like it is working!
Tested with: v5.0-beta.Z.2021lunch
