### ISSUE TITLE
Look Down Axis in Viewscene Broken

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2169]
Problem: The look down axis functionality/drop downs are not working.
Expected behavior: When you select the look down axis there should be a dropdown for which axis to orient up and which to orient towards the camera (look down).
Actual Behavior: When you select the drop down menu nothing drops down and it will seemingly randomly move the view.

**Comment by jab0707** [comment]
Version: v5.0-beta.Y.RC1-3-g3643a82f5

**Comment by dcwhite** [comment]
This seems to break every month. Not surprised it’s here again.

**Comment by dcwhite** [comment]
I replicated this one, then rebuilt, and then it was working again. Mysterious.

**Comment by dcwhite** [comment]
@jab0707 Can you replicate consistently, and with a video attachment? Thanks

**Comment by jab0707** [comment]
Well, when you ask like that it works fine.
I figured out the problem. I was trying to do the second drop down before the first one. See the below video
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38257234/91912058-8c719380-ec6f-11ea-9379-96146d6c8aa5.gif)

**Comment by jab0707** [comment]
Well, when you ask like that it works fine.
I figured out the problem. I was trying to do the second drop down before the first one. See the below video. Although it still looks down the wrong axis (usually if you say positive it does negative, unless "looking down" means make it point away from the camera which seems backwards)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/38257234/91912162-cb074e00-ec6f-11ea-89cb-5387d6203430.gif)

**Comment by dcwhite** [comment]
I found the underlying problem. When that toolbar is clicked in a disabled state, or off of the actual comboboxes, the renderer registers a drag/rotate, like when clicking anywhere else in the "exposed" viewer. That's the tiny "random rotation" you're seeing. To stop that from happening we'd have to move where that toolbar pops up. Is that too annoying to avoid? I made sure when the combobox is empty, no rotation happens, and it's disabled until it's filled, but the "random rotation" still happens due to the toolbar being in a floating state above the renderer.
