### ISSUE TITLE
String input port on AutoReadFile

### ISSUE THREAD

**Issue by jab0707** [SCIInstitute/SCIRun#2270]
I would like a string input on the AutoReadFile module which would behave as it does for readfield or readmatrix. The thing should be treated like a file path that is used to tell the module what file to load.

**Comment by dcwhite** [comment]
AutoReadFile is supposed to be for quick GUI use rather than scripting, to save time when loading data for prototyping. Once a network is mature enough to be scripted around, why can't ReadMatrix or ReadField be used instead, where this functionality is already present? The file types you're working with would be known and fixed at that point. Is there a need to be able to load different types of file from the same module starting point within the script (which AutoReadFile would handle better)?
