### ISSUE TITLE
Verify that EvaluateLinAlgUnary does not write to invalid SparseMatrix location

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#482]
Verify that [SCIRun 4 bug #874](https://gforge.sci.utah.edu/gf/project/cibc/tracker/?action=TrackerItemEdit&tracker_item_id=874&start=0) does not apply to new EvaluateLinAlgUnary implementation.

**Comment by dcwhite** [comment]
This is still a problem in v5. Eigen handles it better, but the real issue is multithreading of the Parser code with sparse matrices--there needs to be a critical section around each sparse matrix access, and this really slows down the parallel engine. A better design is required, which will come later. For now, I error out when the parser is used with either EvalLinAlg module and the input matrix(ces) are sparse and too big (I picked >10000 elements).

**Comment by aylakhan** [comment]
Sure, let's do a code review after IBBM.
