### ISSUE TITLE
Parser crashes

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/SCIRun#847]
the parser for CalculateFieldData crashes scirun when some variables are call more than once.  this is a legacy problem from SCIRun 4 but it is quite annoying.  I will make an example network.

**Comment by dcwhite** [comment]
@jessdtate Could this come up during IBBM? If you attach a link to a network, I can probably fix the bug.

**Comment by jessdtate** [comment]
This bug is only and issue when you try to assign a variable to RESULT after it has been called before. Here is an example or parser code that crashes SCIRun:
dist=X*X+Y*Y+Z*Z;
d2=dist*dist;
RESULT=dist*dist;
This can be run with a CreateLatVol for testing.

It has something to do with the operations, because If the last line is 'RESULT=dist;', then there is no crash.  The work around is to be really careful about variables that you assign as outputs.

**Comment by dcwhite** [comment]
Thanks, I'll check this one out too.

**Comment by dcwhite** [comment]
I added null checks so the above won't crash, but the module still errors. It's a failed precondition of the parser logic, possibly due to overoptimization. A full fix will take a lot of time to dig through the parser library, so that will have to wait. I improved the error message so that the user might be able to fix their parser code to avoid this situation.
