### ISSUE TITLE
ViewScene doesn't initialize properly about 10-20% of the time

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/SCIRun#881]
Related to the promise system for retrieving assets, we believe. @iauns really needs to take a look.

**Comment by dcwhite** [comment]
I took a tour down the rabbit hole and didn't really get anywhere.

**Comment by dcwhite** [comment]
@aylakhan @cbrightsci Adding some capture code for this error which will stop the rendering loop if the axes don't get initialized after 50 frames. The slot turns the ViewScene module widget red. Testing it by adding multiple ViewScenes to an empty network reveals the error percentage is around 5%, but more often when it's the first one.

**Comment by dcwhite** [comment]
See https://github.com/SCIInstitute/SCIRun/commit/b855797ac55212602be00f756012189fd822eb8e

**Comment by dcwhite** [comment]
@jessdtate IBBM

**Comment by aylakhan** [comment]
This is on @cbrightsci's renderer technical objectives list.

**Comment by dcwhite** [comment]
I'm going to take another crack at this one since it was quite prevalent at this year's IBBM.

**Comment by iauns** [comment]
I vaguely recall this from a while back. I remember thinking that we needed to reduce the complexity of the start up process and reduce the logic to something straight-forward. It also makes it easier if your rendering logic blocks for assets instead of using intermediates or waiting for them to load (SCIRun probably doesn't have a large number of assets to load or differing LODs for the individual objects). It also allows you to debug startup problems easier when looking at the command buffers generated by the user-mode OpenGL driver since you don't have initialization code spread over time. Feel free to ping me. I'll be in Utah this coming weekend if you want another pair of eyes on it.

**Comment by dcwhite** [comment]
Thanks! But alas, I'll be in New York this weekend.

**Comment by iauns** [comment]
Regardless, if you have any questions ping me via email or messenger and we can work through it.

**Comment by dcwhite** [comment]
I burrowed a little bit deeper this time, and found a race condition occurring in the initialization phase, related to `ComponentContainer` and its `renormalize` function. I can write up a detailed report if you want.

**Comment by aylakhan** [comment]
That would be a good idea.

**Comment by dcwhite** [comment]
If we fix this, #738 will probably be resolved. So I'll close that one and just reference it here for testing.

**Comment by dcwhite** [comment]
Will pair-debug with @jessdtate later this year.

**Comment by dcwhite** [comment]
@jessdtate Claude Code Fable 5/Ultracode solved this one in a matter of minutes, just by looking at a static snapshot that contained the bug plus my band-aid (which it used as a hint, it turned out). I'll write up a report on this fun exercise for this week's meeting.
